[0m19:19:06.572942 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f73892336e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f7389d591f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f738954bce0>]}


============================== 19:19:06.597801 | 6d30f51d-3dc7-43c3-9401-f4cb7472ef8b ==============================
[0m19:19:06.597801 [info ] [MainThread]: Running with dbt=1.9.0
[0m19:19:06.606839 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': '/root/.dbt', 'log_path': 'logs', 'version_check': 'True', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt init my_project', 'log_format': 'default', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m19:19:06.725421 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse logging event dictionary. Failed to parse dir field: expected string or bytes-like object, got 'PosixPath'.. Dictionary: {'dir': PosixPath('/root/.dbt')}
[0m19:19:06.733348 [info ] [MainThread]: Creating dbt configuration folder at 
[0m19:19:06.747304 [debug] [MainThread]: Starter project path: /usr/local/lib/python3.12/site-packages/dbt/include/starter_project
[0m19:19:07.285637 [info ] [MainThread]: 
Your new dbt project "my_project" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m19:19:07.292377 [info ] [MainThread]: Setting up your profile.
[0m19:20:45.604020 [info ] [MainThread]: Profile my_project written to /root/.dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m19:20:45.618174 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 99.271484, "process_in_blocks": "0", "process_kernel_time": 0.756738, "process_mem_max_rss": "93164", "process_out_blocks": "1472", "process_user_time": 5.038946}
[0m19:20:45.625661 [debug] [MainThread]: Command `dbt init` succeeded at 19:20:45.625299 after 99.28 seconds
[0m19:20:45.629194 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f738954a9c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f7388bfec30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f7388a43c20>]}
[0m19:20:45.633881 [debug] [MainThread]: Flushing usage events
[0m19:20:46.113142 [debug] [MainThread]: An error was encountered while trying to flush usage events
